### ISSUE TITLE
Github Actions bit rot

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/labscript-suite#55]
New builds using GitHub Actions are now displaying the following message:

> The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

We should fix this!

**Comment by philipstarkey** [comment]
This is now blocking builds, see https://github.com/labscript-suite/labscript-utils/actions/runs/451707676

**Comment by chrisjbillington** [comment]
Thanks for the reminder, I'll take a look today!

**Comment by philipstarkey** [comment]
Thanks! I'd completely forgotten about it until I made a tiny fix directly to master and it fell over. Thought it was my fault for a moment :P

**Comment by chrisjbillington** [comment]
Checklist for fixing this in various repos (may not be relevant for all of them):

- [x] blacs: fixed in labscript-suite/blacs#83
- [ ] desktop-app
- [ ] labscript
- [ ] labscript-c-extensions
- [ ] labscript-devices
- [ ] labscript-suite
- [ ] lyse
- [ ] qtutils
- [ ] runmanager
- [ ] runviewer
- [ ] setuptools-conda
- [ ] vendored-conda-builds
- [ ] workflow-sandbox
- [ ] zprocess

Will merge some other changes such as setuptools-scm version schemes and Python 3.9 releases before backporting these changes to maintenance branches.

**Comment by chrisjbillington** [comment]
This is done at least in the master branches of all repos.

Lots of issues with things not building still though:

* Anaconda cloud client upload is broken on Python 3.9 - solution: use the Python version that ships with the default miniconda (currently 3.8) where conda tools are more well-tested.
* Something about GitHub's Windows image changed in November such that some repos cannot build windows packages, depending on the *length of the name of the project* (causing something to hit up against max filepath lengths). Solution: install miniconda to somewhere with a shorter filepath, use a temporary directory with a short filepath to do build work in `vendored-conda-builds` (the latter doesn't seem necessary for other projects).
* New MacOS SDK is not yet supported by conda tools, so one needs to tell the GitHub workflow to use an older one. In fact, it's good to use the oldest minor version GitHub actions supports, since that will keep things compatible with more versions of MacOS. So we should specify to use the oldest one, upgrading each time GItHub actions drops support for a minor version.

So I'm working on an update to our "standard" workflow that will address these issues, and then will push it out to everything.
