### ISSUE TITLE
Bitrot in workflows

### ISSUE THREAD

**Issue by dihm** [labscript-suite/labscript-suite#75]
Looking at the action logs for the [latest labscript-utils release](https://github.com/labscript-suite/labscript-utils/actions/runs/4538025605), there appears to be a fair bit of bitrot that is about to crash the builds. Would be nice to get ahead of these issues before then.

- node.js 12 in setup-miniconda action is deprecated
- `set-output` command is deprecated
- `repository_url` needs to be changed to `repository-url`
- pip publishing action is no longer supported, should be switched from master branch to release

**Comment by chrisjbillington** [comment]
I've updated workflows and made releases for `zprocess`, `desktop-app`, `setuptools-conda` and `vendored-conda-builds`. Because this includes all the impure packages, `labscript-suite` is now installable on Python 3.11.

We'll need to update the workflow for all repos, and some are well due for a release (`labscript-suite` *installs*, but BLACS doesn't start, for example, due to a bug long since fixed in `labscript-devices` but without a new release 😬).

Remaining to think about are:

- [ ] blacs
- [ ] labscript
- [ ] labscript-devices (https://github.com/labscript-suite/labscript-devices/pull/105/)
- [ ] labscript-suite
- [ ] lyse
- [ ] runmanager
- [ ] runviewer
- [ ] qtutils

**Comment by dihm** [comment]
Thanks for bumping all the releases and versions! Keeping up with all of this can be quite annoying. When I get back from vacation next week, I'll go ahead and update the workflows for all the remaining modules.

> (labscript-suite installs, but BLACS doesn't start, for example, due to a bug long since fixed in labscript-devices but without a new release 😬).

Well that's embarrassing, but I'll choose to pretend this was an intentional test of how many people install fresh from the pinned versions instead of editable main branches. I guess the answer is still very few ;)

**Comment by dihm** [comment]
Ugh. Made all those PRs and forgot to update the python versions in setup.cfg for all of them.
